/**
 * Clawtrace — Bug Report Generator Module
 * ============================================================
 * One-click formatted bug report generation from any trace.
 * Outputs in GitHub Issue markdown, Jira format, or plain text.
 * Includes: summary, steps, errors, analyzer findings, trace snippet.
 * ============================================================
 */
'use strict';

var Clawtrace = Clawtrace || {};

Clawtrace.BugReport = (function () {

    var S = Clawtrace.Sanitizer;

    var _container = null;

    /* ---- Initialize ---- */

    function init(container) {
        _container = container;
    }

    /* ---- Generate Report Data ---- */

    function generateReportData(traceData, analysisResult) {
        if (!traceData || !traceData.steps) {
            return null;
        }

        var steps = traceData.steps;
        var analysis = analysisResult || {};

        // Extract key info
        var errorSteps = [];
        var toolCalls = [];
        var totalTokens = 0;

        for (var i = 0; i < steps.length; i++) {
            var step = steps[i];
            var contentLen = (step.content || '').length;
            totalTokens += Math.ceil(contentLen / 4);

            if (step.type === 'error') {
                errorSteps.push({ index: i + 1, content: (step.content || '').substring(0, 200) });
            }
            if (step.type === 'tool_call') {
                var toolName = (step.metadata && step.metadata.tool_name) ? step.metadata.tool_name : 'unknown';
                toolCalls.push({ index: i + 1, name: toolName });
            }
        }

        // Detect model
        var detectedModel = 'Unknown';
        for (var m = 0; m < steps.length; m++) {
            if (steps[m].metadata && steps[m].metadata.model) {
                detectedModel = steps[m].metadata.model;
                break;
            }
        }

        // High-severity warnings
        var criticalWarnings = [];
        if (analysis.warnings) {
            for (var w = 0; w < analysis.warnings.length; w++) {
                if (analysis.warnings[w].level === 'critical' || analysis.warnings[w].level === 'error') {
                    criticalWarnings.push(analysis.warnings[w]);
                }
            }
        }

        // Trace snippet (first/last few steps)
        var snippetSteps = [];
        var maxSnippet = Math.min(steps.length, 4);
        for (var s = 0; s < maxSnippet; s++) {
            snippetSteps.push({
                index: s + 1,
                type: steps[s].type,
                summary: (steps[s].summary || steps[s].content || '').substring(0, 100)
            });
        }
        if (steps.length > 4) {
            snippetSteps.push({ index: steps.length, type: steps[steps.length - 1].type, summary: (steps[steps.length - 1].summary || steps[steps.length - 1].content || '').substring(0, 100) });
        }

        return {
            totalSteps: steps.length,
            riskScore: analysis.riskScore || 0,
            confidenceScore: analysis.confidenceScore || 0,
            errors: errorSteps,
            toolCalls: toolCalls,
            detectedModel: detectedModel,
            totalTokens: totalTokens,
            criticalWarnings: criticalWarnings,
            snippetSteps: snippetSteps,
            findingsCount: analysis.findings ? analysis.findings.length : 0
        };
    }

    /* ---- Format: GitHub Issue ---- */

    function formatGitHub(data) {
        var lines = [];

        lines.push('## Bug Report — AI Trace Analysis');
        lines.push('');
        lines.push('**Generated by [Clawtrace](https://github.com/DosukaSOL/clawtrace)**');
        lines.push('');

        lines.push('### Summary');
        lines.push('');
        lines.push('| Metric | Value |');
        lines.push('|--------|-------|');
        lines.push('| Total Steps | ' + data.totalSteps + ' |');
        lines.push('| Risk Score | ' + data.riskScore + '/100 |');
        lines.push('| Confidence Score | ' + data.confidenceScore + '/100 |');
        lines.push('| Estimated Tokens | ' + data.totalTokens.toLocaleString() + ' |');
        lines.push('| Detected Model | ' + data.detectedModel + ' |');
        lines.push('| Tool Calls | ' + data.toolCalls.length + ' |');
        lines.push('| Errors | ' + data.errors.length + ' |');
        lines.push('| Findings | ' + data.findingsCount + ' |');
        lines.push('');

        if (data.errors.length > 0) {
            lines.push('### Errors Detected');
            lines.push('');
            for (var e = 0; e < Math.min(data.errors.length, 5); e++) {
                lines.push('**Step #' + data.errors[e].index + ':**');
                lines.push('```');
                lines.push(data.errors[e].content);
                lines.push('```');
                lines.push('');
            }
        }

        if (data.criticalWarnings.length > 0) {
            lines.push('### Critical Warnings');
            lines.push('');
            for (var w = 0; w < data.criticalWarnings.length; w++) {
                lines.push('- **' + data.criticalWarnings[w].title + '**: ' + (data.criticalWarnings[w].detail || ''));
            }
            lines.push('');
        }

        if (data.toolCalls.length > 0) {
            lines.push('### Tool Calls');
            lines.push('');
            for (var t = 0; t < Math.min(data.toolCalls.length, 10); t++) {
                lines.push('- Step #' + data.toolCalls[t].index + ': `' + data.toolCalls[t].name + '`');
            }
            lines.push('');
        }

        lines.push('### Trace Snippet');
        lines.push('');
        for (var s = 0; s < data.snippetSteps.length; s++) {
            var step = data.snippetSteps[s];
            lines.push('**#' + step.index + ' [' + step.type.toUpperCase() + ']**: ' + step.summary);
        }
        if (data.totalSteps > 5) {
            lines.push('_... and ' + (data.totalSteps - 5) + ' more steps_');
        }
        lines.push('');

        lines.push('### Environment');
        lines.push('');
        lines.push('- **Tool**: Clawtrace v1.1.0');
        lines.push('- **Date**: ' + new Date().toISOString().split('T')[0]);
        lines.push('- **Browser**: ' + (navigator.userAgent || 'Unknown').substring(0, 100));
        lines.push('');

        return lines.join('\n');
    }

    /* ---- Format: Jira ---- */

    function formatJira(data) {
        var lines = [];

        lines.push('h2. Bug Report \u2014 AI Trace Analysis');
        lines.push('');
        lines.push('_Generated by [Clawtrace|https://github.com/DosukaSOL/clawtrace]_');
        lines.push('');

        lines.push('h3. Summary');
        lines.push('||Metric||Value||');
        lines.push('|Total Steps|' + data.totalSteps + '|');
        lines.push('|Risk Score|' + data.riskScore + '/100|');
        lines.push('|Confidence Score|' + data.confidenceScore + '/100|');
        lines.push('|Estimated Tokens|' + data.totalTokens.toLocaleString() + '|');
        lines.push('|Detected Model|' + data.detectedModel + '|');
        lines.push('|Errors|' + data.errors.length + '|');
        lines.push('');

        if (data.errors.length > 0) {
            lines.push('h3. Errors Detected');
            for (var e = 0; e < Math.min(data.errors.length, 5); e++) {
                lines.push('*Step #' + data.errors[e].index + ':*');
                lines.push('{code}');
                lines.push(data.errors[e].content);
                lines.push('{code}');
                lines.push('');
            }
        }

        if (data.criticalWarnings.length > 0) {
            lines.push('h3. Critical Warnings');
            for (var w = 0; w < data.criticalWarnings.length; w++) {
                lines.push('* *' + data.criticalWarnings[w].title + '*: ' + (data.criticalWarnings[w].detail || ''));
            }
            lines.push('');
        }

        lines.push('h3. Environment');
        lines.push('* *Tool*: Clawtrace v1.1.0');
        lines.push('* *Date*: ' + new Date().toISOString().split('T')[0]);
        lines.push('');

        return lines.join('\n');
    }

    /* ---- Format: Plain Text ---- */

    function formatPlainText(data) {
        var lines = [];

        lines.push('BUG REPORT — AI Trace Analysis');
        lines.push('Generated by Clawtrace (https://github.com/DosukaSOL/clawtrace)');
        lines.push('========================================');
        lines.push('');

        lines.push('SUMMARY');
        lines.push('-------');
        lines.push('Total Steps:      ' + data.totalSteps);
        lines.push('Risk Score:       ' + data.riskScore + '/100');
        lines.push('Confidence Score: ' + data.confidenceScore + '/100');
        lines.push('Estimated Tokens: ' + data.totalTokens.toLocaleString());
        lines.push('Detected Model:   ' + data.detectedModel);
        lines.push('Tool Calls:       ' + data.toolCalls.length);
        lines.push('Errors:           ' + data.errors.length);
        lines.push('Findings:         ' + data.findingsCount);
        lines.push('');

        if (data.errors.length > 0) {
            lines.push('ERRORS DETECTED');
            lines.push('---------------');
            for (var e = 0; e < Math.min(data.errors.length, 5); e++) {
                lines.push('Step #' + data.errors[e].index + ': ' + data.errors[e].content);
            }
            lines.push('');
        }

        if (data.criticalWarnings.length > 0) {
            lines.push('CRITICAL WARNINGS');
            lines.push('-----------------');
            for (var w = 0; w < data.criticalWarnings.length; w++) {
                lines.push('- ' + data.criticalWarnings[w].title + ': ' + (data.criticalWarnings[w].detail || ''));
            }
            lines.push('');
        }

        lines.push('ENVIRONMENT');
        lines.push('-----------');
        lines.push('Tool:    Clawtrace v1.1.0');
        lines.push('Date:    ' + new Date().toISOString().split('T')[0]);
        lines.push('');

        return lines.join('\n');
    }

    /* ---- Render UI ---- */

    function render(traceData, analysisResult) {
        if (!_container) { return; }

        while (_container.firstChild) {
            _container.removeChild(_container.firstChild);
        }

        var data = generateReportData(traceData, analysisResult);

        if (!data) {
            var empty = S.createElement('p', { 'class': 'no-data' }, 'Load and analyze a trace first to generate a bug report.');
            _container.appendChild(empty);
            return;
        }

        // Header
        var header = S.createElement('div', { 'class': 'bugreport-header' });
        var title = S.createElement('h3', { 'class': 'bugreport-title' }, '\uD83D\uDCCB One-Click Bug Report');
        var desc = S.createElement('p', { 'class': 'bugreport-desc' }, 'Generate a formatted bug report from the current trace analysis. Choose your format and copy to clipboard.');
        header.appendChild(title);
        header.appendChild(desc);
        _container.appendChild(header);

        // Format buttons
        var btnGroup = S.createElement('div', { 'class': 'bugreport-btn-group' });

        var formats = [
            { id: 'github', label: '\uD83D\uDC19 GitHub Issue', format: 'github' },
            { id: 'jira', label: '\uD83D\uDCCB Jira', format: 'jira' },
            { id: 'plaintext', label: '\uD83D\uDCC4 Plain Text', format: 'plaintext' }
        ];

        for (var f = 0; f < formats.length; f++) {
            var btn = S.createElement('button', {
                'class': 'btn btn-primary bugreport-format-btn' + (f === 0 ? ' active' : ''),
                'data-format': formats[f].format
            }, formats[f].label);
            btnGroup.appendChild(btn);
        }

        _container.appendChild(btnGroup);

        // Output area
        var outputWrap = S.createElement('div', { 'class': 'bugreport-output-wrap' });
        var output = S.createElement('pre', { 'class': 'bugreport-output', 'id': 'bugreport-output' });
        S.safeSetText(output, formatGitHub(data));
        outputWrap.appendChild(output);
        _container.appendChild(outputWrap);

        // Copy button
        var copyBtn = S.createElement('button', { 'class': 'btn btn-primary bugreport-copy-btn', 'id': 'bugreport-copy' }, '\uD83D\uDCCB Copy to Clipboard');
        _container.appendChild(copyBtn);

        // Status message
        var status = S.createElement('div', { 'class': 'bugreport-status', 'id': 'bugreport-status' });
        _container.appendChild(status);

        // Bind events
        bindEvents(data);
    }

    /* ---- Event Binding ---- */

    function bindEvents(data) {
        var outputEl = document.getElementById('bugreport-output');
        var copyBtn = document.getElementById('bugreport-copy');
        var statusEl = document.getElementById('bugreport-status');
        var formatBtns = _container.querySelectorAll('.bugreport-format-btn');

        // Format switching
        for (var i = 0; i < formatBtns.length; i++) {
            formatBtns[i].addEventListener('click', function (e) {
                var format = e.currentTarget.getAttribute('data-format');
                var text = '';

                if (format === 'github') { text = formatGitHub(data); }
                else if (format === 'jira') { text = formatJira(data); }
                else { text = formatPlainText(data); }

                if (outputEl) { S.safeSetText(outputEl, text); }

                // Update active button
                for (var j = 0; j < formatBtns.length; j++) {
                    formatBtns[j].classList.remove('active');
                }
                e.currentTarget.classList.add('active');
            });
        }

        // Copy to clipboard
        if (copyBtn) {
            copyBtn.addEventListener('click', function () {
                var text = outputEl ? outputEl.textContent : '';
                if (!text) { return; }

                if (navigator.clipboard && navigator.clipboard.writeText) {
                    navigator.clipboard.writeText(text).then(function () {
                        showStatus(statusEl, 'Copied to clipboard!', 'success');
                    }).catch(function () {
                        showStatus(statusEl, 'Failed to copy. Please select and copy manually.', 'error');
                    });
                } else {
                    // Fallback
                    try {
                        var ta = document.createElement('textarea');
                        ta.value = text;
                        ta.style.position = 'fixed';
                        ta.style.left = '-9999px';
                        document.body.appendChild(ta);
                        ta.select();
                        document.execCommand('copy');
                        document.body.removeChild(ta);
                        showStatus(statusEl, 'Copied to clipboard!', 'success');
                    } catch (err) {
                        showStatus(statusEl, 'Failed to copy. Please select and copy manually.', 'error');
                    }
                }
            });
        }
    }

    function showStatus(el, msg, type) {
        if (!el) { return; }
        S.safeSetText(el, msg);
        el.className = 'bugreport-status bugreport-status-' + type;
        setTimeout(function () {
            S.safeSetText(el, '');
            el.className = 'bugreport-status';
        }, 3000);
    }

    /* ---- Public API ---- */

    return {
        init: init,
        render: render,
        formatGitHub: formatGitHub,
        formatJira: formatJira,
        formatPlainText: formatPlainText
    };

})();
