/**
 * Clawtrace — Export Module
 * ============================================================
 * Exports trace data and analysis results in multiple formats:
 * - JSON (raw data)
 * - Markdown (human-readable report)
 * - HTML (printable, self-contained)
 *
 * All exports are generated client-side using Blob URLs.
 * No data is sent to any server.
 * ============================================================
 */
'use strict';

var Clawtrace = Clawtrace || {};

Clawtrace.Export = (function () {

    var S = Clawtrace.Sanitizer;

    /**
     * Exports trace data as a JSON file download.
     *
     * @param {Object} traceData - Parsed trace data
     * @param {Object} analysisResult - Analysis results
     */
    function exportJSON(traceData, analysisResult) {
        if (!traceData) { return; }

        var exportObj = {
            clawtrace: {
                version: '1.0.0',
                exportedAt: new Date().toISOString(),
                generator: 'Clawtrace — AI Interaction & Reasoning Explorer'
            },
            trace: traceData,
            analysis: analysisResult || null
        };

        var json = JSON.stringify(exportObj, null, 2);
        downloadBlob(json, 'clawtrace-export.json', 'application/json');
    }

    /**
     * Exports trace data as a Markdown file.
     *
     * @param {Object} traceData - Parsed trace data
     * @param {Object} analysisResult - Analysis results
     */
    function exportMarkdown(traceData, analysisResult) {
        if (!traceData) { return; }

        var lines = [];

        lines.push('# Clawtrace Export');
        lines.push('');
        lines.push('> Generated by [Clawtrace](https://github.com/DosukaSOL/clawtrace) — AI Interaction & Reasoning Explorer');
        lines.push('> Exported: ' + new Date().toISOString());
        lines.push('');

        // Meta
        lines.push('## Trace Metadata');
        lines.push('');
        lines.push('| Property | Value |');
        lines.push('|----------|-------|');
        lines.push('| Format | ' + S.escapeHTML(traceData.meta.format) + ' |');
        lines.push('| Steps | ' + traceData.steps.length + ' |');
        lines.push('| Input Size | ' + (traceData.meta.inputSize || 0).toLocaleString() + ' chars |');
        lines.push('| Parsed At | ' + S.escapeHTML(traceData.meta.parsedAt) + ' |');
        lines.push('');

        // Analysis
        if (analysisResult) {
            lines.push('## Analysis Results');
            lines.push('');
            lines.push('- **Risk Score:** ' + analysisResult.riskScore + ' / 100');
            lines.push('- **Confidence Score:** ' + analysisResult.confidenceScore + ' / 100');
            lines.push('- **Total Steps:** ' + analysisResult.stats.total);
            lines.push('- **Estimated Tokens:** ' + analysisResult.stats.estimatedTokens.toLocaleString());
            lines.push('');

            // Warnings
            if (analysisResult.warnings.length > 0) {
                lines.push('### Warnings');
                lines.push('');
                for (var w = 0; w < analysisResult.warnings.length; w++) {
                    var warn = analysisResult.warnings[w];
                    var icon = warn.level === 'critical' ? '🔴' :
                               warn.level === 'error' ? '🟠' :
                               warn.level === 'warning' ? '🟡' : 'ℹ️';
                    lines.push(icon + ' **' + S.escapeHTML(warn.title) + '** — ' + S.escapeHTML(warn.detail));
                }
                lines.push('');
            }

            // Findings
            if (analysisResult.findings.length > 0) {
                lines.push('### Findings');
                lines.push('');
                for (var f = 0; f < Math.min(analysisResult.findings.length, 50); f++) {
                    var finding = analysisResult.findings[f];
                    lines.push('- **[' + S.escapeHTML(finding.category) + ']** ' + S.escapeHTML(finding.text));
                    if (finding.evidence) {
                        lines.push('  > ' + S.escapeHTML(finding.evidence));
                    }
                }
                lines.push('');
            }
        }

        // Timeline
        lines.push('## Interaction Timeline');
        lines.push('');

        for (var i = 0; i < traceData.steps.length; i++) {
            var step = traceData.steps[i];
            lines.push('### Step #' + step.index + ' — ' + capitalize(step.type));
            lines.push('');
            lines.push('```');
            // Limit content length in export
            var content = step.content || '';
            if (content.length > 5000) {
                content = content.substring(0, 5000) + '\n[truncated]';
            }
            lines.push(content);
            lines.push('```');
            lines.push('');
        }

        lines.push('---');
        lines.push('*Exported by Clawtrace v1.0.0*');

        var md = lines.join('\n');
        downloadBlob(md, 'clawtrace-export.md', 'text/markdown');
    }

    /**
     * Exports as a self-contained, printable HTML file.
     *
     * @param {Object} traceData - Parsed trace data
     * @param {Object} analysisResult - Analysis results
     */
    function exportHTML(traceData, analysisResult) {
        if (!traceData) { return; }

        var html = [];

        html.push('<!DOCTYPE html>');
        html.push('<html lang="en">');
        html.push('<head>');
        html.push('<meta charset="UTF-8">');
        html.push('<meta name="viewport" content="width=device-width, initial-scale=1.0">');
        html.push('<title>Clawtrace Export</title>');
        html.push('<style>');
        html.push(getExportCSS());
        html.push('</style>');
        html.push('</head>');
        html.push('<body>');

        html.push('<header>');
        html.push('<h1>&#x2756; Clawtrace Export</h1>');
        html.push('<p class="subtitle">AI Interaction &amp; Reasoning Explorer</p>');
        html.push('<p class="meta">Exported: ' + S.escapeHTML(new Date().toISOString()) + '</p>');
        html.push('</header>');

        // Analysis section
        if (analysisResult) {
            html.push('<section class="analysis">');
            html.push('<h2>Analysis Results</h2>');
            html.push('<div class="scores">');
            html.push('<div class="score-card">');
            html.push('<div class="score-value">' + analysisResult.riskScore + '</div>');
            html.push('<div class="score-label">Risk Score</div>');
            html.push('</div>');
            html.push('<div class="score-card">');
            html.push('<div class="score-value">' + analysisResult.confidenceScore + '</div>');
            html.push('<div class="score-label">Confidence</div>');
            html.push('</div>');
            html.push('<div class="score-card">');
            html.push('<div class="score-value">' + analysisResult.stats.total + '</div>');
            html.push('<div class="score-label">Steps</div>');
            html.push('</div>');
            html.push('</div>');

            // Warnings
            if (analysisResult.warnings.length > 0) {
                html.push('<h3>Warnings</h3>');
                html.push('<ul class="warnings">');
                for (var w = 0; w < analysisResult.warnings.length; w++) {
                    var warn = analysisResult.warnings[w];
                    html.push('<li class="warn-' + S.escapeHTML(warn.level) + '">');
                    html.push('<strong>' + S.escapeHTML(warn.title) + '</strong>: ' +
                              S.escapeHTML(warn.detail));
                    html.push('</li>');
                }
                html.push('</ul>');
            }

            html.push('</section>');
        }

        // Timeline
        html.push('<section class="timeline">');
        html.push('<h2>Interaction Timeline</h2>');

        for (var i = 0; i < traceData.steps.length; i++) {
            var step = traceData.steps[i];
            html.push('<div class="step step-' + S.escapeHTML(step.type) + '">');
            html.push('<div class="step-header">');
            html.push('<span class="step-num">#' + step.index + '</span>');
            html.push('<span class="step-type">' + S.escapeHTML(capitalize(step.type)) + '</span>');
            html.push('<span class="step-summary">' + S.escapeHTML(step.summary) + '</span>');
            html.push('</div>');
            html.push('<pre class="step-content">' +
                       S.escapeHTML(truncateContent(step.content, 5000)) +
                       '</pre>');
            html.push('</div>');
        }

        html.push('</section>');

        html.push('<footer>');
        html.push('<p>Generated by Clawtrace v1.0.0 &mdash; 100% client-side &middot; zero tracking</p>');
        html.push('</footer>');

        html.push('</body>');
        html.push('</html>');

        var htmlStr = html.join('\n');
        downloadBlob(htmlStr, 'clawtrace-export.html', 'text/html');
    }

    /**
     * Returns minimal CSS for the exported HTML report.
     */
    function getExportCSS() {
        return [
            '* { box-sizing: border-box; margin: 0; padding: 0; }',
            'body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;',
            '  max-width: 900px; margin: 0 auto; padding: 40px 20px;',
            '  color: #1e293b; background: #f8fafc; line-height: 1.6; }',
            'header { text-align: center; margin-bottom: 40px; }',
            'h1 { font-size: 2rem; color: #4f46e5; }',
            '.subtitle { color: #64748b; margin-top: 4px; }',
            '.meta { font-size: 0.8rem; color: #94a3b8; margin-top: 8px; }',
            'h2 { font-size: 1.4rem; color: #1e293b; margin: 24px 0 12px; padding-bottom: 8px; border-bottom: 1px solid #e2e8f0; }',
            'h3 { font-size: 1.1rem; color: #475569; margin: 16px 0 8px; }',
            '.scores { display: flex; gap: 16px; justify-content: center; margin: 20px 0; }',
            '.score-card { text-align: center; padding: 20px; background: white; border-radius: 8px;',
            '  border: 1px solid #e2e8f0; min-width: 120px; }',
            '.score-value { font-size: 2.5rem; font-weight: 700; color: #4f46e5; }',
            '.score-label { font-size: 0.8rem; color: #64748b; margin-top: 4px; }',
            '.warnings { list-style: none; }',
            '.warnings li { padding: 8px 12px; margin: 4px 0; border-radius: 6px; font-size: 0.9rem; }',
            '.warn-critical { background: rgba(220,38,38,0.08); border-left: 3px solid #dc2626; }',
            '.warn-error { background: rgba(239,68,68,0.08); border-left: 3px solid #ef4444; }',
            '.warn-warning { background: rgba(245,158,11,0.08); border-left: 3px solid #f59e0b; }',
            '.warn-info { background: rgba(59,130,246,0.08); border-left: 3px solid #3b82f6; }',
            '.step { margin: 12px 0; border-radius: 8px; border: 1px solid #e2e8f0; overflow: hidden; background: white; }',
            '.step-header { display: flex; gap: 8px; align-items: center; padding: 10px 14px; background: #f8fafc; }',
            '.step-num { font-family: monospace; font-size: 0.8rem; color: #94a3b8; min-width: 2em; }',
            '.step-type { font-size: 0.75rem; font-weight: 600; text-transform: uppercase;',
            '  padding: 2px 8px; border-radius: 4px; background: #e2e8f0; color: #475569; }',
            '.step-summary { flex: 1; font-size: 0.9rem; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
            '.step-content { padding: 12px 14px; font-size: 0.8rem; white-space: pre-wrap;',
            '  word-break: break-word; max-height: 300px; overflow-y: auto; color: #475569; }',
            '.step-user .step-type { background: #dbeafe; color: #1d4ed8; }',
            '.step-assistant .step-type { background: #e0e7ff; color: #4338ca; }',
            '.step-tool_call .step-type { background: #fef3c7; color: #92400e; }',
            '.step-error .step-type { background: #fee2e2; color: #991b1b; }',
            '.step-reasoning .step-type { background: #ede9fe; color: #6d28d9; }',
            'footer { text-align: center; margin-top: 40px; padding: 20px; color: #94a3b8; font-size: 0.8rem; }',
            '@media print { body { background: white; } .step-content { max-height: none; } }'
        ].join('\n');
    }

    /* ---- Helpers ---- */

    /**
     * Triggers a browser file download from a string blob.
     *
     * @param {string} content - File content
     * @param {string} filename - Download filename
     * @param {string} mimeType - MIME type
     */
    function downloadBlob(content, filename, mimeType) {
        var blob;
        try {
            blob = new Blob([content], { type: mimeType });
        } catch (e) {
            // Fallback for older browsers
            var builder = new (window.BlobBuilder || window.WebKitBlobBuilder ||
                             window.MozBlobBuilder)();
            builder.append(content);
            blob = builder.getBlob(mimeType);
        }

        var url = URL.createObjectURL(blob);
        var link = document.createElement('a');
        link.href = url;
        link.download = filename;
        link.style.display = 'none';
        document.body.appendChild(link);
        link.click();

        // Cleanup
        setTimeout(function () {
            document.body.removeChild(link);
            URL.revokeObjectURL(url);
        }, 100);
    }

    function capitalize(str) {
        if (!str) return '';
        return str.charAt(0).toUpperCase() + str.slice(1);
    }

    function truncateContent(content, maxLen) {
        if (!content) return '';
        if (content.length > maxLen) {
            return content.substring(0, maxLen) + '\n[truncated]';
        }
        return content;
    }

    /* ---- Public API ---- */
    return {
        exportJSON: exportJSON,
        exportMarkdown: exportMarkdown,
        exportHTML: exportHTML
    };

})();
