/**
 * Clawtrace — Trace-to-Issue Pipeline
 * ============================================================
 * Generates GitHub-ready issue templates from trace analysis.
 * Pre-fills steps to reproduce, environment, and trace data.
 *
 * 100% offline · zero dependencies · safe DOM rendering
 * ============================================================
 */
'use strict';

var Clawtrace = Clawtrace || {};

Clawtrace.TraceIssue = (function () {

    var S = Clawtrace.Sanitizer;
    var _container = null;

    function init(container) { _container = container; }

    function render(traceData, analysisResult) {
        if (!_container || !traceData) { return; }
        while (_container.firstChild) { _container.removeChild(_container.firstChild); }

        var issue = buildIssue(traceData, analysisResult);
        renderPreview(issue);
        renderCopyButton(issue);
    }

    function buildIssue(traceData, analysisResult) {
        var steps = traceData.steps;
        var meta = traceData.meta || {};

        // Detect errors
        var errors = [];
        var errorSteps = [];
        for (var i = 0; i < steps.length; i++) {
            if (steps[i].type === 'error') {
                errors.push({
                    step: i + 1,
                    content: (steps[i].content || '').substring(0, 200)
                });
                errorSteps.push(i + 1);
            }
        }

        // Detect model
        var model = 'Not detected';
        for (var m = 0; m < steps.length; m++) {
            var md = steps[m].metadata || {};
            if (md.model) { model = md.model; break; }
        }

        // Build steps to reproduce from user messages
        var userSteps = [];
        for (var u = 0; u < steps.length && userSteps.length < 5; u++) {
            if (steps[u].type === 'user') {
                userSteps.push((steps[u].content || '').substring(0, 150));
            }
        }

        // Detect tool failures
        var failedTools = [];
        for (var t = 0; t < steps.length; t++) {
            if (steps[t].type === 'tool_call') {
                var content = steps[t].content || '';
                if (/error|fail|exception|denied|refused/i.test(content)) {
                    failedTools.push({
                        step: t + 1,
                        tool: content.substring(0, 100)
                    });
                }
            }
        }

        var title = 'Bug: ';
        if (errors.length > 0) {
            title += 'Agent error at step ' + errorSteps[0];
        } else if (failedTools.length > 0) {
            title += 'Tool failure detected';
        } else {
            title += 'Unexpected behavior in trace';
        }

        var body = '## Description\n\n';
        body += 'Clawtrace detected ';
        if (errors.length > 0) { body += errors.length + ' error(s)'; }
        if (failedTools.length > 0) {
            body += (errors.length > 0 ? ' and ' : '') + failedTools.length + ' tool failure(s)';
        }
        if (errors.length === 0 && failedTools.length === 0) { body += 'an issue'; }
        body += ' in the agent trace.\n\n';

        body += '## Environment\n\n';
        body += '- **Model**: ' + S.escapeHTML(model) + '\n';
        body += '- **Steps**: ' + steps.length + '\n';
        if (meta.sessionId) {
            body += '- **Session**: ' + S.escapeHTML(String(meta.sessionId)).substring(0, 30) + '\n';
        }
        body += '- **Analyzer Risk Score**: ' + (analysisResult ? analysisResult.riskScore : 'N/A') + '\n';
        body += '\n';

        body += '## Steps to Reproduce\n\n';
        for (var s = 0; s < userSteps.length; s++) {
            body += (s + 1) + '. ' + S.escapeHTML(userSteps[s]) + '\n';
        }
        body += '\n';

        if (errors.length > 0) {
            body += '## Errors\n\n';
            for (var e = 0; e < errors.length; e++) {
                body += '- **Step ' + errors[e].step + '**: ' + S.escapeHTML(errors[e].content) + '\n';
            }
            body += '\n';
        }

        if (failedTools.length > 0) {
            body += '## Failed Tools\n\n';
            for (var ft = 0; ft < failedTools.length; ft++) {
                body += '- **Step ' + failedTools[ft].step + '**: ' + S.escapeHTML(failedTools[ft].tool) + '\n';
            }
            body += '\n';
        }

        body += '## Trace Summary\n\n';
        body += '- Total steps: ' + steps.length + '\n';
        body += '- Errors: ' + errors.length + '\n';
        body += '- Failed tools: ' + failedTools.length + '\n';
        body += '\n---\n*Generated by [Clawtrace](https://github.com/DosukaSOL/clawtrace) — OpenClaw trace explorer*\n';

        return { title: title, body: body, errors: errors, failedTools: failedTools };
    }

    function renderPreview(issue) {
        var section = S.createElement('div', { 'class': 'ti-preview' });
        var title = S.createElement('h3', { 'class': 'ti-section-title' }, 'Issue Template');
        section.appendChild(title);

        section.appendChild(S.createElement('p', { 'class': 'ti-desc' },
            'This generates a GitHub issue template from the trace analysis. Copy the issue body and paste it into a new issue ' +
            'on the openclaw/openclaw repository or your own project.'));

        // Title preview
        var titleBlock = S.createElement('div', { 'class': 'ti-title-block' });
        titleBlock.appendChild(S.createElement('span', { 'class': 'ti-label' }, 'Issue Title'));
        titleBlock.appendChild(S.createElement('div', { 'class': 'ti-title-text' }, issue.title));
        section.appendChild(titleBlock);

        // Body preview
        var bodyBlock = S.createElement('div', { 'class': 'ti-body-block' });
        bodyBlock.appendChild(S.createElement('span', { 'class': 'ti-label' }, 'Issue Body'));
        var pre = S.createElement('pre', { 'class': 'ti-body-pre' });
        pre.appendChild(S.createElement('code', {}, issue.body));
        bodyBlock.appendChild(pre);
        section.appendChild(bodyBlock);

        _container.appendChild(section);
    }

    function renderCopyButton(issue) {
        var section = S.createElement('div', { 'class': 'ti-actions' });

        var copyBtn = S.createElement('button', { 'class': 'ti-copy-btn' }, 'Copy Issue to Clipboard');
        copyBtn.addEventListener('click', function () {
            var text = '# ' + issue.title + '\n\n' + issue.body;
            try {
                if (navigator.clipboard && navigator.clipboard.writeText) {
                    navigator.clipboard.writeText(text).then(function () {
                        S.safeSetText(copyBtn, 'Copied!');
                        setTimeout(function () { S.safeSetText(copyBtn, 'Copy Issue to Clipboard'); }, 2000);
                    });
                }
            } catch (e) {
                // Clipboard not available — fallback
                S.safeSetText(copyBtn, 'Select text manually');
            }
        });

        section.appendChild(copyBtn);
        _container.appendChild(section);
    }

    return { init: init, render: render };
})();
